name: Construire Ferme Mali APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Construire APK
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v5

      - name: Installer Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.1'
          channel: stable

      - name: Installer les dépendances
        working-directory: ferme_mali
        run: flutter pub get

      - name: Construire APK
        working-directory: ferme_mali
        run: flutter build apk --debug

      - name: Récupérer APK
        uses: actions/upload-artifact@v4
        with:
          name: ferme-mali-test
          path: ferme_mali/build/app/outputs/flutter-apk/app-debug.apk
          Corriger le workflow de construction APK
